### ISSUE TITLE
Error on pupil code

### ISSUE THREAD

**Issue by pavannaikmu** [manujagobind/Iris#1]
Traceback (most recent call last):
  File "E:\im-crop-master\pupil1.py", line 27, in <module>
    _, contours, hierarchy = cv2.findContours(thresh, cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)
ValueError: not enough values to unpack (expected 3, got 2)

**Comment by pavannaikmu** [comment]
Traceback (most recent call last):
File "E:\im-crop-master\pupil1.py", line 27, in
_, contours, hierarchy = cv2.findContours(thresh, cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)
ValueError: not enough values to unpack (expected 3, got 2)
